# Generated by Django 4.0 on 2021-12-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='')),
                ('title', models.CharField(default='', max_length=200)),
                ('detail', models.CharField(default='', max_length=200)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
    ]
